// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // NOTE: the installed @prisma/config (7.9.1) datasource type only accepts
  // `url`, so DIRECT_URL isn't wired here yet. Point DATABASE_URL at the
  // direct (non-pooled) Supabase connection string when running migrations
  // locally; switch to the pooled URL for the deployed app's runtime env.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
